"use client";
import { useMemo, useState } from "react";
import { Table2, Columns3, List, Plus, Search, SlidersHorizontal, ArrowDownAZ, X, FileText, CalendarDays, Trash2, UserRound, Circle } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { newRow, priorities, statuses, type Page, type Row } from "@/lib/model";
const statusClass = (status: string) => status === "Done" ? "done" : status === "In progress" ? "progress" : "not-started";
export default function Database({ page, onChange }: { page: Page; onChange: (rows: Row[]) => void }) {
  const [view, setView] = useState<"table" | "board" | "list">("table"); const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All statuses"); const [filterOpen, setFilterOpen] = useState(false); const [sort, setSort] = useState(false); const [detailId, setDetailId] = useState<string | null>(null);
  const [dragged, setDragged] = useState<string | null>(null);
  const rows = useMemo(() => { const filtered = page.rows.filter(r => (filter === "All statuses" || r.status === filter) && `${r.title} ${r.assignee} ${r.notes}`.toLowerCase().includes(query.toLowerCase())); return sort ? [...filtered].sort((a, b) => a.title.localeCompare(b.title)) : filtered; }, [page.rows, query, filter, sort]);
  const detail = page.rows.find(r => r.id === detailId);
  function update(id: string, changes: Partial<Row>) { onChange(page.rows.map(r => r.id === id ? { ...r, ...changes } : r)); }
  function add(status?: Row["status"]) { const row = newRow(); row.status = status ?? (filter !== "All statuses" ? filter as Row["status"] : "Not started"); onChange([...page.rows, row]); setDetailId(row.id); }
  function statusSelect(row: Row) { return <span className={`status-badge ${statusClass(row.status)}`}><Circle size={8} fill="currentColor" /><select aria-label={`Status of ${row.title}`} value={row.status} onChange={e => update(row.id, { status: e.target.value as Row["status"] })}>{statuses.map(s => <option key={s}>{s}</option>)}</select></span>; }
  return <section className="database" aria-label="Database">
    <div className="database-toolbar"><div className="view-tabs" role="tablist" aria-label="Database views">{[{ id: "table", label: "Table", icon: Table2 }, { id: "board", label: "Board", icon: Columns3 }, { id: "list", label: "List", icon: List }].map(v => <button key={v.id} role="tab" aria-selected={view === v.id} className={view === v.id ? "active" : ""} onClick={() => setView(v.id as typeof view)}><v.icon size={16} />{v.label}</button>)}</div><div className="database-actions"><div className="database-search"><Search size={15} /><input placeholder="Search…" aria-label="Search database" value={query} onChange={e => setQuery(e.target.value)} /></div><button className={`icon-button ${filter !== "All statuses" ? "active-control" : ""}`} aria-label="Filter database" aria-expanded={filterOpen} onClick={() => setFilterOpen(!filterOpen)}><SlidersHorizontal size={16} /></button><button className={`icon-button ${sort ? "active-control" : ""}`} aria-label="Sort by name" aria-pressed={sort} onClick={() => setSort(!sort)}><ArrowDownAZ size={16} /></button><button className="primary small-button" onClick={() => add()}><Plus size={14} />New</button></div></div>
    {filterOpen && <div className="filter-bar"><span>Status is</span><select aria-label="Filter by status" value={filter} onChange={e => setFilter(e.target.value)}>{["All statuses", ...statuses].map(s => <option key={s}>{s}</option>)}</select><button className="icon-button" aria-label="Clear filter" onClick={() => { setFilter("All statuses"); setFilterOpen(false); }}><X size={15} /></button></div>}
    {view === "table" && <div className="table-scroll"><table className="database-table"><thead><tr><th><span className="property-type">Aa</span>Name</th><th><Circle size={13} />Status</th><th><SlidersHorizontal size={13} />Priority</th><th><UserRound size={13} />Assignee</th><th><CalendarDays size={13} />Due date</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><button className="row-open" aria-label={`Open ${row.title}`} onClick={() => setDetailId(row.id)}><FileText size={16} /></button><input aria-label={`Name of ${row.title}`} value={row.title} placeholder="Untitled" onChange={e => update(row.id, { title: e.target.value })} /></td><td>{statusSelect(row)}</td><td><select className={`priority-badge priority-${row.priority.toLowerCase()}`} aria-label={`Priority of ${row.title}`} value={row.priority} onChange={e => update(row.id, { priority: e.target.value as Row["priority"] })}>{priorities.map(p => <option key={p}>{p}</option>)}</select></td><td><input aria-label={`Assignee of ${row.title}`} placeholder="Unassigned" value={row.assignee} onChange={e => update(row.id, { assignee: e.target.value })} /></td><td><input type="date" aria-label={`Due date of ${row.title}`} value={row.due} onChange={e => update(row.id, { due: e.target.value })} /></td></tr>)}</tbody></table><button className="new-row" onClick={() => add()}><Plus size={15} />New item</button></div>}
    {view === "board" && <div className="kanban">{statuses.map(status => <div key={status} className={`kanban-column ${dragged ? "drop-ready" : ""}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragged) update(dragged, { status }); setDragged(null); }}><div className="kanban-header"><span className={`status-badge ${statusClass(status)}`}><Circle size={8} fill="currentColor" />{status}</span><span className="column-count">{rows.filter(r => r.status === status).length}</span><button className="icon-button" aria-label={`Add task to ${status}`} onClick={() => add(status)}><Plus size={15} /></button></div>{rows.filter(r => r.status === status).map(row => <article key={row.id} className="kanban-card" draggable onDragStart={e => { setDragged(row.id); e.dataTransfer.setData("text/plain", row.id); }} onDragEnd={() => setDragged(null)}><button className="card-title" onClick={() => setDetailId(row.id)}><FileText size={16} />{row.title || "Untitled"}</button><div className="card-properties"><span className={`priority-badge priority-${row.priority.toLowerCase()}`}>{row.priority}</span>{row.assignee && <span className="card-assignee"><span className="avatar small">{row.assignee[0]}</span>{row.assignee}</span>}</div>{row.due && <div className="card-date"><CalendarDays size={13} />{row.due}</div>}<div className="card-status">{statusSelect(row)}</div></article>)}<button className="new-row" onClick={() => add(status)}><Plus size={15} />New item</button></div>)}</div>}
    {view === "list" && <div className="database-list">{rows.map(row => <div key={row.id}><button className="list-title" onClick={() => setDetailId(row.id)}><FileText size={17} />{row.title || "Untitled"}</button>{statusSelect(row)}<span className={`priority-badge priority-${row.priority.toLowerCase()}`}>{row.priority}</span></div>)}<button className="new-row" onClick={() => add()}><Plus size={15} />New item</button></div>}
    {!rows.length && <div className="database-empty"><Table2 size={26} /><p>{page.rows.length ? "No items match your filters." : "Your next project starts with one task."}</p>{page.rows.length > 0 && <button onClick={() => { setQuery(""); setFilter("All statuses"); }}>Clear filters</button>}</div>}
    <div className="database-summary">{rows.length} of {page.rows.length} items<span>{page.rows.filter(r => r.status === "Done").length} completed</span></div>
    <Dialog open={!!detail} onOpenChange={open => { if (!open) setDetailId(null); }}><DialogContent className="nf-dialog row-dialog"><DialogHeader><DialogTitle>Task details</DialogTitle><DialogDescription>Edit properties and capture the details.</DialogDescription></DialogHeader>{detail && <><input className="task-title" aria-label="Task name" value={detail.title} placeholder="Untitled" onChange={e => update(detail.id, { title: e.target.value })} /><div className="task-properties"><label>Status{statusSelect(detail)}</label><label>Priority<select value={detail.priority} onChange={e => update(detail.id, { priority: e.target.value as Row["priority"] })}>{priorities.map(p => <option key={p}>{p}</option>)}</select></label><label>Assignee<input placeholder="Unassigned" value={detail.assignee} onChange={e => update(detail.id, { assignee: e.target.value })} /></label><label>Due date<input type="date" value={detail.due} onChange={e => update(detail.id, { due: e.target.value })} /></label></div><label className="notes-label">Notes<textarea placeholder="Add context, links, or a few thoughts…" value={detail.notes} onChange={e => update(detail.id, { notes: e.target.value })} /></label><button className="danger delete-task" onClick={() => { onChange(page.rows.filter(r => r.id !== detail.id)); setDetailId(null); }}><Trash2 size={15} />Delete task</button></>}</DialogContent></Dialog>
  </section>;
}
